"""initial postgres schema with celery task id

Revision ID: 346ef72f2f3d
Revises: 
Create Date: 2026-06-07 11:36:32.440034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346ef72f2f3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_task_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_job_results_status'), ['status'], unique=False)
        batch_op.create_index('ix_job_results_status_updated', ['status', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_results', schema=None) as batch_op:
        batch_op.drop_index('ix_job_results_status_updated')
        batch_op.drop_index(batch_op.f('ix_job_results_status'))
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('celery_task_id')

    # ### end Alembic commands ###
